<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;


class StudentMTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('users')->insert([
            [
                'id'=> '1000',
                'name' => 'Andrew Cole',
                'email' => 'andrew.cole@strathmore.edu',
                'password' => Hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 

            ],
            [
                'id'=> '1001',
                'name' => 'Faith Njambi Njaramba',
                'email' => 'faith.njaramba@strathmore.edu',
                'password' => Hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111228',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 

            ],
            [
                'id'=> '1002',
                'name' => 'Mary Moraa Aminga',
                'email' => 'mary.moraa@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111229',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id'=> '1003',
                'name' => 'Ndung\'u, Joan Wanjiku',
                'email' => 'joan.wanjiku@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111234',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 

            ],
            [
                'id'=> '1004',
                'name' => 'Ngaruiya, Jane Wangari',
                'email' => 'jane.ngaruiya@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111244',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id'=> '1005',
                'name' => 'Simon Kanji',
                'email' => 'simon.kanji@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111254',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id'=> '1006',
                'name' => 'Anita Njemo Musiega',
                'email' => 'anita.musiega@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111264',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1007',
                'name' => 'Raymond Ochieng’',
                'email' => 'raymond.ochieng@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111274',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1008',
                'name' => 'Fidelis Udahemuka',
                'email' => 'fidelis.udahemuka@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111284',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1009',
                'name' => 'Salome Oyuga',
                'email' => 'salome.oyuga@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111294',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1010',
                'name' => 'Edwin Obonyo',
                'email' => 'edwin.obonyo@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111324',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1011',
                'name' => 'Judy Gichuki',
                'email' => 'judy.gichuki@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111424',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1012',
                'name' => 'Sidi Mpa Mwakalu',
                'email' => 'mpa.sidi@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111524',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1013',
                'name' => 'Kemal Ahmed Hussein',
                'email' => 'ahmed.kemal@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111624',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [   'id' => '1014',
                'name' => 'Joyce Kiarie',
                'email' => 'joyce.kiarie@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111724',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [   'id' => '1015',
                'name' => 'Ajwang Akoth Morine',
                'email' => 'morine.ajwang@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111824',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [   'id' => '1016',
                'name' => 'Bojo Samuel Scopas',
                'email' => 'samuel.bojo@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111924',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1017',
                'name' => 'Kariuki, Kellen Eileen',
                'email' => 'kellen.kariuki@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711112224',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1018',
                'name' => 'James Oreyo Odero',
                'email' => 'james.odero@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711112222',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
        
            [
                'id' => '1019',
                'name' => 'Nkinyili T. Tabulu',
                'email' => 'tabulu.nkinyili@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711112223',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1020',
                'name' => 'Stacey Kwamboka Orangi',
                'email' => 'stacey.orangi@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711112225',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1021',
                'name' => 'Simon Peter Njuguna Muthoni',
                'email' => 'simon.njuguna@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711112226',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1022',
                'name' => 'Eunice Kiumi',
                'email' => 'eunice.kiumi@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1023',
                'name' => 'Andrew Ngurumi',
                'email' => 'andrew.ngurumi@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1024',
                'name' => 'Lorna Shuma',
                'email' => 'lorna.shuma@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1025',
                'name' => 'Irene Maithya',
                'email' => 'irene.maithya@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1026',
                'name' => 'George Nabina',
                'email' => 'george.nabina@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1027',
                'name' => 'Shila Nhemi',
                'email' => 'shila.nhemi@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
        ]);
    }
}
