<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;


class StudentMTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('users')->insert([
            [
                'id'=> '1000',
                'name' => 'Andrew Cole',
                'email' => 'omandi@strathmore.edu',
                'password' => Hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 

            ],
            [
                'id'=> '1001',
                'name' => 'Faith Njambi Njaramba',
                'email' => 'faith.njaramba@strathmore.edu',
                'password' => Hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111228',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 

            ],
            [
                'id'=> '1002',
                'name' => 'Mary Moraa Aminga',
                'email' => 'mary.moraa@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111229',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id'=> '1003',
                'name' => 'Ndungu, Joan Wanjiku',
                'email' => 'joan.wanjiku@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111234',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 

            ],
            [
                'id'=> '1004',
                'name' => 'Ngaruiya, Jane Wangari',
                'email' => 'jane.ngaruiya@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111244',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id'=> '1005',
                'name' => 'Simon Kanji',
                'email' => 'simon.kanji@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111254',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id'=> '1006',
                'name' => 'Anita Njemo Musiega',
                'email' => 'anitamusiega@gmail.com',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111264',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1007',
                'name' => 'Raymond Ochieng’',
                'email' => 'rochieng@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111274',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1008',
                'name' => 'Fidelis Udahemuka',
                'email' => 'fidelis.udahemuka@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111284',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1009',
                'name' => 'Salome Oyuga',
                'email' => 'salome.oyuga@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111294',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1010',
                'name' => 'Edwin Obonyo',
                'email' => 'edwin.obonyo@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111324',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1011',
                'name' => 'Judy Gichuki',
                'email' => 'judy.gichuki@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111424',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1012',
                'name' => 'Sidi Mpa Mwakalu',
                'email' => 'sidimpa@gmail.com',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111524',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1013',
                'name' => 'Kemal Ahmed Hussein',
                'email' => 'ahmed.kemal@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111624',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [   'id' => '1014',
                'name' => 'Joyce Kiarie',
                'email' => 'jckiarie@gmail.com',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111724',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [   'id' => '1015',
                'name' => 'Ajwang Akoth Morine',
                'email' => 'makoth@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111824',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [   'id' => '1016',
                'name' => 'Bojo Samuel Scopas',
                'email' => 'bojolokiden@gmail.com',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711111924',
                'date_of_birth' => '1970-01-01',
                'country_id' => '165',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1017',
                'name' => 'Kariuki, Kellen Eileen',
                'email' => 'kellen.kariuki@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711112224',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1018',
                'name' => 'James Oreyo Odero',
                'email' => 'james.odero@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711112222',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
        
            [
                'id' => '1019',
                'name' => 'Nkinyili T. Tabulu',
                'email' => 'tabulu.nkinyili@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711112223',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1020',
                'name' => 'Stacey Kwamboka Orangi',
                'email' => 'stacey.orangi@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711112225',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1021',
                'name' => 'Simon Peter Njuguna Muthoni',
                'email' => 'snjuguna@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711112226',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1022',
                'name' => 'Eunice Kiumi',
                'email' => 'eunice.kiumi@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1023',
                'name' => 'Andrew Ngurumi',
                'email' => 'andrew.ngurumi@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1024',
                'name' => 'Lorna Shuma',
                'email' => 'lorna.shuma@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1025',
                'name' => 'Irene Maithya',
                'email' => 'irene.maithya@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1026',
                'name' => 'George Nabina',
                'email' => 'george.nabina@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1027',
                'name' => 'Shila Nhemi',
                'email' => 'shila.nhemi@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1028',
                'name' => 'Alaka Benard Ochieng',
                'email' => 'benard.alaka@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],

            [
                'id' => '1029',
                'name' => 'Mutua Elizabeth Ndunge',
                'email' => 'elizabeth.ndunge@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],

            [
                'id' => '1030',
                'name' => 'Thomas Julius Oduor',
                'email' => 'julius.oduor@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1031',
                'name' => 'Kirui Chepngeno Julliet',
                'email' => 'julliet.kirui@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1032',
                'name' => 'Mundama Alfadjiri Benjamin',
                'email' => 'alfadjiri.benjamin@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1033',
                'name' => 'Mwongela Stanslaus Wambua',
                'email' => 'stanslaus.wambua@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1034',
                'name' => 'Nkinyili, Tiberius Tabulu',
                'email' => 'tiberius.tabulu@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1035',
                'name' => 'Kinyua Wallace Muchiri',
                'email' => 'wallace.muchiri@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1036',
                'name' => 'Manyasi Eunice Engefu',
                'email' => 'eunice.manyasi@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1037',
                'name' => 'Omondi Kevin Ochieng',
                'email' => 'kevin.ochieng@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1038',
                'name' => 'Gikera James Njihia',
                'email' => 'james.njihiag@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1039',
                'name' => 'Tunduny, Titus Kipkosgei',
                'email' => 'titus.tunduny@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1040',
                'name' => 'Shailja Sharma',
                'email' => 'shailja.sharma@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1041',
                'name' => 'Anthony Wachira',
                'email' => 'anthony.wachira@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1042',
                'name' => 'Belinda Korir',
                'email' => 'belinda.korir@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1043',
                'name' => 'Benson Otieno Obol',
                'email' => 'benson.obol@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1044',
                'name' => 'Judith Njumwah Kariuki',
                'email' => 'judith.kariuki@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1045',
                'name' => 'Bylhah Mugotitsa',
                'email' => 'bylhah.mugotitsa@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1046',
                'name' => 'Christine Awuor',
                'email' => 'christine.awuor@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1047',
                'name' => 'Daniel Ogola',
                'email' => 'daniel.ogola@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1048',
                'name' => 'Carolyne Waithira Mukuha',
                'email' => 'carolyne.mukuha@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1049',
                'name' => 'Diriba Feyisa Demu',
                'email' => 'feyisa.demu@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1050',
                'name' => 'Ezekiel Meteine Karino',
                'email' => 'ezeliel.karino@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1051',
                'name' => 'Rosalind Kirika',
                'email' => 'rosalind.kirika@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1052',
                'name' => 'Juliana Muteti',
                'email' => 'jmuteti@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1053',
                'name' => 'Mercy Inyangala Omuyoma',
                'email' => 'mkano@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],

            [
                'id' => '1054',
                'name' => 'Philip Neri',
                'email' => 'pneri@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1055',
                'name' => 'Eric Kioko Tama',
                'email' => 'etama@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1056',
                'name' => 'Daniel Isoso Machanje',
                'email' => 'dmachanje@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1056',
                'name' => 'Daniel Isoso Machanje',
                'email' => 'dmachanje@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1057',
                'name' => 'Maritim Ann Chemutai',
                'email' => 'achemutai@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1058',
                'name' => 'Daniel Isoso Machanje',
                'email' => 'dmachanje@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1059',
                'name' => 'Shabaya Patrick',
                'email' => 'pshabaya@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1060',
                'name' => 'Shadrack Muli Munyithia',
                'email' => 'mulishadrack@gmail.com',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1061',
                'name' => 'William Kipkemboi Kirwa',
                'email' => 'wkirwa@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1062',
                'name' => 'Collins Hagai',
                'email' => 'chaggai@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1063',
                'name' => 'Fr. Rafael Wokorach',
                'email' => 'wokoraphael@gmail.com',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1064',
                'name' => 'Nicodemus Nzoka Maingi',
                'email' => 'nmaingi@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1065',
                'name' => 'Mutune Loraine Ndinda',
                'email' => 'loraineyvonne@gmail.com',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1066',
                'name' => 'Lucy Njogu',
                'email' => 'luchiru@gmail.com',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1067',
                'name' => 'Kevin Otieno',
                'email' => 'kotieno@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1068',
                'name' => 'Grace Ikahu',
                'email' => 'muchangigrace@gmail.com',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1069',
                'name' => 'Leunora Okubasu',
                'email' => 'aronuel@gmail.com',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1070',
                'name' => 'Wase Benti',
                'email' => 'wasebenti3@gmail.com',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '59',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1071',
                'name' => 'John Patrick Micheni',
                'email' => 'pmichemi@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1073',
                'name' => 'Oda Gebeyehu Dejene',
                'email' => 'betyyegebe@gmail.com',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '59',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1072',
                'name' => 'Job Jagongo',
                'email' => 'jobjagongo92@gmail.com',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1074',
                'name' => 'Leonard Mabele',
                'email' => 'lmabele@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1075',
                'name' => 'Sharon Analo Okwomi',
                'email' => 'sharonokwomi@gmail.com',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1076',
                'name' => 'Kevin Wairagu Muchemi',
                'email' => 'kmuchemi@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1077',
                'name' => 'Speranza A Wangari Migue',
                'email' => 'smigue@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1078',
                'name' => 'John Ogutu Osumba',
                'email' => 'josumba@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1079',
                'name' => 'John Ocheche',
                'email' => 'jocheche@strathmore.edu',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1080',
                'name' => 'Paul Kithikii Musingila',
                'email' => 'paul.musingila@gmail.com',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1081',
                'name' => 'Collins Onyango Oduor',
                'email' => 'coduor@gmail.com',//not indicated
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1082',
                'name' => 'Brian Nyasagare',
                'email' => 'bnyasagarea@gmail.com',//not indicated
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1083',
                'name' => 'Juliana Talai',
                'email' => 'tulatalai@gmail.com',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '1084',
                'name' => 'Jacques Muthusi Kimeu',
                'email' => 'mwj6@cdc.gov',
                'password' => hash::make ('password'),
                'role_id' => '1',
                'phone_number' => '0711122227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png', 
            ],
            [
                'id' => '2000',
                'name' => 'John Njane',
                'email' => 'john.njane@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000000',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2001',
                'name' => 'Hilderlith Ogutu',
                'email' => 'hilderlith.ogutu@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000001',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2002',
                'name' => 'Loise Wanjiru Oburu',
                'email' => 'loise.oburu@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000002',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2004',
                'name' => 'Wairimu Gakuo',
                'email' => 'wairimu.gakuo@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000004',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2005',
                'name' => 'Otieno, Geoffrey Peter',
                'email' => 'geoffrey.otieno@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000005',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2007',
                'name' => 'Kasimu, Paul',
                'email' => 'paul.kasimu@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000007',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2008',
                'name' => 'Kwaka,Truphosa Akinyi',
                'email' => 'truphosa.kwaka@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000008',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2010',
                'name' => 'Owuor Ezekiel Otieno',
                'email' => 'ezekiel.owuor@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000010',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2012',
                'name' => 'Odiko Terah Bobi',
                'email' => 'terah.odiko@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000012',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2013',
                'name' => 'Makau, Charles Kavita',
                'email' => 'charles.makau@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000013',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2014',
                'name' => 'Otieno, Stephen Ouma',
                'email' => 'stephen.otieno@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000014',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2015',
                'name' => 'Beatrice Misorimaligayo',
                'email' => 'beatrice.misorimaligayo@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000015',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2016',
                'name' => 'Brian Gachichio Karanja',
                'email' => 'brian.karanja@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000016',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2017',
                'name' => 'Edwin Obonyo',
                'email' => 'edwin.obonyo@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000017',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2019',
                'name' => 'Joseph Karanu',
                'email' => 'joseph.karanu@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000019',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2020',
                'name' => 'Loice Vihenda Wafula',
                'email' => 'loice.wafula@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000020',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2021',
                'name' => 'Lydia Virginia Muthoki',
                'email' => 'lydia.muthoki@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000015',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2022',
                'name' => 'Noah Otinga',
                'email' => 'noah.otinga@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000022',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2023',
                'name' => 'Ruth N. Mulwa',
                'email' => 'ruth.mulwa@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000023',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2024',
                'name' => 'Lucy Njoki Maru',
                'email' => 'lucy.maru@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000024',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2025',
                'name' => 'Dorcas Awiti Otieno',
                'email' => 'dorcas.otieno@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000025',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2026',
                'name' => 'Fredrick James Otieno',
                'email' => 'fredrick.otieno@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000026',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2027',
                'name' => 'John Kibowen Sergon',
                'email' => 'john.sergon@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000027',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2028',
                'name' => 'Felix Mogesa',
                'email' => 'felix.mogesa@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000028',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2029',
                'name' => 'Josphat Manani',
                'email' => 'josphat.manani@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000029',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2030',
                'name' => 'Linda Ingari',
                'email' => 'linda.ingari@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000030',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2031',
                'name' => 'Simon Kanji',
                'email' => 'simon.kanji@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000031',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2032',
                'name' => 'Sophie Naliaka Kibanani',
                'email' => 'sophie.kibanani@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000032',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
 
            [
                'id' => '2034',
                'name' => 'Oscar Correia',
                'email' => 'oscar.correia@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000034',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2035',
                'name' => 'Melissa Mwiti',
                'email' => 'melissa.mwiti@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000035',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2036',
                'name' => 'Mary Nkoimu Naliki',
                'email' => 'mary.naliki@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000036',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2037',
                'name' => 'Allan Mutuma Gitonga',
                'email' => 'allan.gitonga@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000037',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2038',
                'name' => 'Anthony Mulisa',
                'email' => 'anthony.mulisa@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000038',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2039',
                'name' => 'Timothy Ndikwe',
                'email' => 'timothy.ndikwe@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000039',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
  
            [
                'id' => '2041',
                'name' => 'Kenneth Ogendo',
                'email' => 'kenneth.ogendo@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000041',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2042',
                'name' => 'Hamida Omar Juma',
                'email' => 'hamida.juma@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '0700000042',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            
            [
                'id' => '2043',
                'name' => 'Kashambo, Barry',
                'email' => 'kashambo.barry@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002043',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2044',
                'name' => 'Al Kindy, Samar',
                'email' => 'al.kindy.samar@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002044',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' =>'1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2045',
                'name' => 'Bhayani, Deep',
                'email' => 'bhayani.deep@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002045',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2046',
                'name' => 'Din, Toseef',
                'email' => 'din.toseef@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002046',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2047',
                'name' => 'Esan, Folayinka',
                'email' => 'esan.folayinka@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002047',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2048',
                'name' => 'Gitonga, Raphael',
                'email' => 'gitonga.raphael@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002048',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2049',
                'name' => 'Nzioki, Fredrick',
                'email' => 'nzioki.fredrick@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002049',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2050',
                'name' => 'Mbatha, Anne',
                'email' => 'mbatha.anne@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002050',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2051',
                'name' => 'Mwangi, Esther',
                'email' => 'mwangi.esther@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002051',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2052',
                'name' => 'Kisire, Sharon',
                'email' => 'kisire.sharon@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002052',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2053',
                'name' => 'Mwangi, Naomi May',
                'email' => 'mwangi.naomi.may@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002053',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2054',
                'name' => 'Onsongo, Susan',
                'email' => 'onsongo.susan@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002054',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2055',
                'name' => 'Muriithi, Grace',
                'email' => 'muriithi.grace@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002055',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2056',
                'name' => 'Ikua, Wandia',
                'email' => 'ikua.wandia@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002056',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2057',
                'name' => 'Owusu, David',
                'email' => 'owusu.david@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002057',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2058',
                'name' => 'Gachoki, Lena',
                'email' => 'gachoki.lena@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002058',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2059',
                'name' => 'Koross, Samson',
                'email' => 'koross.samson@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002059',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2060',
                'name' => 'Muthoni, Hilda',
                'email' => 'muthoni.hilda@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002060',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2061',
                'name' => 'Murwa, Rhoda',
                'email' => 'murwa.rhoda@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002061',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2062',
                'name' => 'Rutenge, Justice',
                'email' => 'rutenge.justice@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002062',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2063',
                'name' => 'Aziz, Mwita',
                'email' => 'aziz.mwita@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002063',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2064',
                'name' => 'Wachira, Irene Wagaki',
                'email' => 'wachira.irene.wagaki@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002064',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2065',
                'name' => 'Keino, Florence',
                'email' => 'keino.florence@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002065',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2066',
                'name' => 'Nshekanabo, Frederick',
                'email' => 'nshekanabo.frederick@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002066',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2067',
                'name' => 'Willy Innocent, Twishime',
                'email' => 'willy.innocent.twishime@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002067',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2068',
                'name' => 'Ng\'ang\'a, Judah',
                'email' => 'nganga.judah@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002068',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2069',
                'name' => 'Chepkoit, Chris',
                'email' => 'chepkoit.chris@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002069',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2070',
                'name' => 'Nwobi, Nneka',
                'email' => 'n wobi.nneka@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002070',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2071',
                'name' => 'Murimi, Beatrice',
                'email' => 'murimi.beatrice@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002071',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            [
                'id' => '2072',
                'name' => 'Wakwoma, Winfred',
                'email' => 'wakwoma.winfred@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '1',
                'phone_number' => '07000002072',
                'date_of_birth' => '1990-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                'profile' => 'public/images/user.png'
            ],
            
        ]);
    }
}
