<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class SupervisorMTableSeeder extends Seeder
{

    public function run()
    {
        DB::table('users')->insert([
            [
                'id' => '3000',
                'name' => 'Prof. Livingstone Luboobi',
                'email' => 'l.luboobi@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711111111',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                
            ],
            [
                'name' => 'Prof. Rachel Mbogo',
                'email' => 'r.mbogo@strathmore.edu',
                'role_id' => '2',
                'password' => Hash::make('password'),
                'phone_number' => '0722222222',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                
            ],
            [
                'name' => 'Prof. Lyle Mckinnon',
                'email' => 'l.mckinnon@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0733333333',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                
            ],
            [
                'name' => 'Prof. Daniel Skarlicki',
                'email' => 'd.skarlicki@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0744444444',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                //'school_id'=>'1',
            ],
            [
                'name' => 'Dr. John Olukuru',
                'email' => 'j.olukuru@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0755555555',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                //'school_id'=>'1',
            ],
            [
                'name' => 'Prof. Jonathan Annan',
                'email' => 'j.annan@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0766666666',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                //'school_id'=>'1',
            ],
            [
                'name' => 'Prof. Reuben Marwanga',
                'email' => 'r.marwanga@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0777777777',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                //'school_id'=>'1',
            ],
            [
                'name' => 'Prof. Vertinsky, Ilan',
                'email' => 'v.ilan@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0788888888',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                //'school_id'=>'1',
            ],
            [
                'name' => 'Dr. Joseph Onyango',
                'email' => 'j.onyango@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0799999999',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                //'school_id'=>'1',
            ],
            [
                'name' => 'Prof. Pat Obi',
                'email' => 'p.obi@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711111112',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                //'school_id'=>'1',
            ],
            [
                'name' => 'Dr. David Mathuva',
                'email' => 'd.mathuva@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711111113',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                //'school_id'=>'1',
            ],
            [
                'name' => 'Dr. Ankit Katrodia',
                'email' => 'a.katrodia@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711111114',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
               // 'school_id'=>'1',
            ],
            [
                'name' => 'Dr. Fredrick Ogola',
                'email' => 'f.ogola@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711111115',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                //'school_id'=>'1',
            ],
            [
                'name' => 'Dr. Edwine Barasa',
                'email' => 'e.barasa@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711111116',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                //'school_id'=>'1',
            ],
            [
                'name' => 'Prof. Sassy Molyneux',
                'email' => 's.molyneux@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711111117',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                //'school_id'=>'1',
            ],
            [
                'name' => 'Dr. Benjamin Tsofa',
                'email' => 'b.tsofa@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711111118',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                //'school_id'=>'1',
            ],
            [
                'name' => 'Prof. Vitalis Onyango Otieno',
                'email' => 'v.onyango@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711111119',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                
            ],
            [
                'name' => 'Prof. Maurice Owino Oduor',
                'email' => 'm.oduor@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711111122',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                
            ],
            [
                'name' => 'Prof. Fred Walumbwa',
                'email' => 'f.walumbwa@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711111133',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                //'school_id'=>'1',
            ],
            [
                'name' => 'Dr. Ben Ngoye',
                'email' => 'b.ngoye@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711111144',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                //'school_id'=>'1',
            ],
            [
                'name' => 'Prof. Edward Ochieng',
                'email' => 'e.ochieng@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711111155',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                //'school_id'=>'1',
            ],
            [
                'name' => 'Prof. Geoffrey M. Ngene',
                'email' => 'g.ngene@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711111166',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                //'school_id'=>'1',
            ],
            [
                'name' => 'Prof. Marco Formentini',
                'email' => 'm.formentini@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711111177',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                //'school_id'=>'1',
            ],
            [
                'name' => 'Prof. Simon Ndiritu',
                'email' => 's.ndiritu@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711111188',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                //'school_id'=>'1',
            ],
            [
                'name' => 'Prof. Francis Wafula',
                'email' => 'f.wafula@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711111199',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                //'school_id'=>'1',
            ],
            [
                'name' => 'Dr. Vincent Omwenga',
                'email' => 'v.omwenga@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711111223',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                //'school_id'=>'7',
            ],
            [
                'name' => 'Prof. Patrick Ogao',
                'email' => 'p.ogao@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711111224',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                //'school_id'=>'7',
            ],
            [
                'name' => 'Prof. Gilbert Kokwaro',
                'email' => 'g.kokwaro@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711111225',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                //'school_id'=>'1',
            ],
            [
                'name' => 'Prof. Getnet Mitike Kassie',
                'email' => 'g.kassie@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711111226',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                //'school_id'=>'1',
            ],
            [
                'name' => 'Prof. Samuel Mwalili',
                'email' => 's.mwalili@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711112227',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                
            ],
            [
                'name' => 'Prof. John Odhiambo',
                'email' => 'j.odhiambo@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711112228',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                
            ],
            [
                'name' => 'Prof. Ambrose Agweyu',
                'email' => 'a.agweyu@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711112229',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                
            ],
            [
                'name' => 'Prof. Ruth Kiraka',
                'email' => 'r.kiraka@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711122221',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                
            ],
            [
                'name' => 'Prof. Bernard Omolo',
                'email' => 'b.omolo@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711122222',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                
            ],
            [
                'name' => 'Dr. Hellen Otieno',
                'email' => 'h.otieno@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711122223',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                
            ],
            [
                'name' => 'Prof. David Wang\'ombe',
                'email' => 'd.wang\'ombe@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711122224',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                
            ],
            [
                'name' => 'Dr. Farida Abdul',
                'email' => 'f.abdul@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711122225',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                
            ],
            [
                'name' => 'Prof. Kofi Dadzie',
                'email' => 'k.dadzie@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711122226',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                
            ],
            [
                'name' => 'Dr. Elizabeth Mokeira',
                'email' => 'e.mokeira@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711122228',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                //'school_id'=>'4',
            ],
            [
                'name' => 'Dr. Francis Kariuki',
                'email' => 'f.kariuki@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711122229',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '1',
                'status' => 'active',
                //'school_id'=>'4',
            ],
            [
                'name' => 'Dr. Jane Wathuta',
                'email' => 'j.wathuta@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711222221',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                //'school_id'=>'4',
            ],
            [
                'name' => 'Dr. Elizabeth Gachenga',
                'email' => 'e.gachenga@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711222222',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                //'school_id'=>'4',
            ],
            [
                'name' => 'Dr. Jackson Bett',
                'email' => 'j.bett@strathmore.edu',
                'password' => Hash::make('password'),
                'role_id' => '2',
                'phone_number' => '0711222223',
                'date_of_birth' => '1970-01-01',
                'country_id' => '89',
                'religion_id' => '1',
                'gender_id' => '2',
                'status' => 'active',
                //'school_id'=>'4',
            ],
        ]);
    }
}
