<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('country', function (Blueprint $table) {
            $table->id();
            $table->string('country_name');
            $table->string('nationality');
            $table->string('country_code');
            $table->timestamps();
        });
         // Populate data
         $data = [
            ['Afghanistan', 'Afghan', '93'],
            ['Albania', 'Albanian', '355'],
            ['Algeria', 'Algerian', '213'],
            ['Andorra', 'Andorran', '376'],
            ['Angola', 'Angolan', '244'],
            ['Antigua and Barbuda', 'Antiguan', '1-268'],
            ['Argentina', 'Argentine', '54'],
            ['Armenia', 'Armenian', '374'],
            ['Australia', 'Australian', '61'],
            ['Austria', 'Austrian', '43'],
            ['Azerbaijan', 'Azerbaijani', '994'],
            ['Bahamas', 'Bahamian', '1-242'],
            ['Bahrain', 'Bahraini', '973'],
            ['Bangladesh', 'Bangladeshi', '880'],
            ['Barbados', 'Barbadian', '1-246'],
            ['Belarus', 'Belarusian', '375'],
            ['Belgium', 'Belgian', '32'],
            ['Belize', 'Belizean', '501'],
            ['Benin', 'Beninese', '229'],
            ['Bhutan', 'Bhutanese', '975'],
            ['Bolivia', 'Bolivian', '591'],
            ['Bosnia and Herzegovina', 'Bosnian', '387'],
            ['Botswana', 'Motswana', '267'],
            ['Brazil', 'Brazilian', '55'],
            ['Brunei', 'Bruneian', '673'],
            ['Bulgaria', 'Bulgarian', '359'],
            ['Burkina Faso', 'Burkinabe', '226'],
            ['Burundi', 'Burundian', '257'],
            ['Cabo Verde', 'Cabo Verdean', '238'],
            ['Cambodia', 'Cambodian', '855'],
            ['Cameroon', 'Cameroonian', '237'],
            ['Canada', 'Canadian', '1'],
            ['Central African Republic', 'Central African', '236'],
            ['Chad', 'Chadian', '235'],
            ['Chile', 'Chilean', '56'],
            ['China', 'Chinese', '86'],
            ['Colombia', 'Colombian', '57'],
            ['Comoros', 'Comoran', '269'],
            ['Congo [Congo-Brazzaville]', 'Congolese', '242'],
            ['Costa Rica', 'Costa Rican', '506'],
            ['Cote d\'Ivoire [Ivory Coast]', 'Ivorian', '225'],
            ['Croatia', 'Croatian', '385'],
            ['Cuba', 'Cuban', '53'],
            ['Cyprus', 'Cypriot', '357'],
            ['Czech Republic', 'Czech', '420'],
            ['Democratic Republic of the Congo [Congo-Kinshasa]', 'Congolese', '243'],
            ['Denmark', 'Danish', '45'],
            ['Djibouti', 'Djiboutian', '253'],
            ['Dominica', 'Dominican', '1-767'],
            ['Dominican Republic', 'Dominican', '1-809, 1-829, 1-849'],
            ['East Timor [Timor-Leste]', 'Timorese', '670'],
            ['Ecuador', 'Ecuadorian', '593'],
            ['Egypt', 'Egyptian', '20'],
            ['El Salvador', 'Salvadoran', '503'],
            ['Equatorial Guinea', 'Equatorial Guinean', '240'],
            ['Eritrea', 'Eritrean', '291'],
            ['Estonia', 'Estonian', '372'],
            ['Eswatini [fmr. Swaziland]', 'Swazi', '268'],
            ['Ethiopia', 'Ethiopian', '251'],
            ['Fiji', 'Fijian', '679'],
            ['Finland', 'Finnish', '358'],
            ['France', 'French', '33'],
            ['Gabon', 'Gabonese', '241'],
            ['Gambia', 'Gambian', '220'],
            ['Georgia', 'Georgian', '995'],
            ['Germany', 'German', '49'],
            ['Ghana', 'Ghanaian', '233'],
            ['Greece', 'Greek', '30'],
            ['Grenada', 'Grenadian', '1-473'],
            ['Guatemala', 'Guatemalan', '502'],
            ['Guinea', 'Guinean', '224'],
            ['Guinea-Bissau', 'Bissau-Guinean', '245'],
            ['Guyana', 'Guyanese', '592'],
            ['Haiti', 'Haitian', '509'],
            ['Honduras', 'Honduran', '504'],
            ['Hungary', 'Hungarian', '36'],
            ['Iceland', 'Icelander', '354'],
            ['India', 'Indian', '91'],
            ['Indonesia', 'Indonesian', '62'],
            ['Iran', 'Iranian', '98'],
            ['Iraq', 'Iraqi', '964'],
            ['Ireland', 'Irish', '353'],
            ['Israel', 'Israeli', '972'],
            ['Italy', 'Italian', '39'],
            ['Jamaica', 'Jamaican', '1-876'],
            ['Japan', 'Japanese', '81'],
            ['Jordan', 'Jordanian', '962'],
            ['Kazakhstan', 'Kazakhstani', '7'],
            ['Kenya', 'Kenyan', '254'],
            ['Kiribati', 'I-Kiribati', '686'],
            ['Kosovo', 'Kosovar', '383'],
            ['Kuwait', 'Kuwaiti', '965'],
            ['Kyrgyzstan', 'Kyrgyz', '996'],
            ['Laos', 'Laotian', '856'],
            ['Latvia', 'Latvian', '371'],
            ['Lebanon', 'Lebanese', '961'],
            ['Lesotho', 'Mosotho', '266'],
            ['Liberia', 'Liberian', '231'],
            ['Libya', 'Libyan', '218'],
            ['Liechtenstein', 'Liechtensteiner', '423'],
            ['Lithuania', 'Lithuanian', '370'],
            ['Luxembourg', 'Luxembourger', '352'],
            ['Madagascar', 'Malagasy', '261'],
            ['Malawi', 'Malawian', '265'],
            ['Malaysia', 'Malaysian', '60'],
            ['Maldives', 'Maldivian', '960'],
            ['Mali', 'Malian', '223'],
            ['Malta', 'Maltese', '356'],
            ['Marshall Islands', 'Marshallese', '692'],
            ['Mauritania', 'Mauritanian', '222'],
            ['Mauritius', 'Mauritian', '230'],
            ['Mexico', 'Mexican', '52'],
            ['Micronesia', 'Micronesian', '691'],
            ['Moldova', 'Moldovan', '373'],
            ['Monaco', 'Monacan', '377'],
            ['Mongolia', 'Mongolian', '976'],
            ['Montenegro', 'Montenegrin', '382'],
            ['Morocco', 'Moroccan', '212'],
            ['Mozambique', 'Mozambican', '258'],
            ['Myanmar [Burma]', 'Burmese', '95'],
            ['Namibia', 'Namibian', '264'],
            ['Nauru', 'Nauruan', '674'],
            ['Nepal', 'Nepalese', '977'],
            ['Netherlands', 'Dutch', '31'],
            ['New Zealand', 'New Zealander', '64'],
            ['Nicaragua', 'Nicaraguan', '505'],
            ['Niger', 'Nigerien', '227'],
            ['Nigeria', 'Nigerian', '234'],
            ['North Korea', 'North Korean', '850'],
            ['North Macedonia [fmr. Macedonia]', 'Macedonian', '389'],
            ['Norway', 'Norwegian', '47'],
            ['Oman', 'Omani', '968'],
            ['Pakistan', 'Pakistani', '92'],
            ['Palau', 'Palauan', '680'],
            ['Palestine', 'Palestinian', '970'],
            ['Panama', 'Panamanian', '507'],
            ['Papua New Guinea', 'Papua New Guinean', '675'],
            ['Paraguay', 'Paraguayan', '595'],
            ['Peru', 'Peruvian', '51'],
            ['Philippines', 'Filipino', '63'],
            ['Poland', 'Polish', '48'],
            ['Portugal', 'Portuguese', '351'],
            ['Qatar', 'Qatari', '974'],
            ['Romania', 'Romanian', '40'],
            ['Russia', 'Russian', '7'],
            ['Rwanda', 'Rwandan', '250'],
            ['Saint Kitts and Nevis', 'Kittitian/Nevisian', '1-869'],
            ['Saint Lucia', 'Saint Lucian', '1-758'],
            ['Saint Vincent and the Grenadines', 'Vincentian', '1-784'],
            ['Samoa', 'Samoan', '685'],
            ['San Marino', 'Sammarinese', '378'],
            ['Sao Tome and Principe', 'Sao Tomean', '239'],
            ['Saudi Arabia', 'Saudi Arabian', '966'],
            ['Senegal', 'Senegalese', '221'],
            ['Serbia', 'Serbian', '381'],
            ['Seychelles', 'Seychellois', '248'],
            ['Sierra Leone', 'Sierra Leonean', '232'],
            ['Singapore', 'Singaporean', '65'],
            ['Slovakia', 'Slovak', '421'],
            ['Slovenia', 'Slovene', '386'],
            ['Solomon Islands', 'Solomon Islander', '677'],
            ['Somalia', 'Somali', '252'],
            ['South Africa', 'South African', '27'],
            ['South Korea', 'South Korean', '82'],
            ['South Sudan', 'South Sudanese', '211'],
            ['Spain', 'Spanish', '34'],
            ['Sri Lanka', 'Sri Lankan', '94'],
            ['Sudan', 'Sudanese', '249'],
            ['Suriname', 'Surinamese', '597'],
            ['Sweden', 'Swedish', '46'],
            ['Switzerland', 'Swiss', '41'],
            ['Syria', 'Syrian', '963'],
            ['Taiwan', 'Taiwanese', '886'],
            ['Tajikistan', 'Tajik', '992'],
            ['Tanzania', 'Tanzanian', '255'],
            ['Thailand', 'Thai', '66'],
            ['Togo', 'Togolese', '228'],
            ['Tonga', 'Tongan', '676'],
            ['Trinidad and Tobago', 'Trinidadian/Tobagonian', '1-868'],
            ['Tunisia', 'Tunisian', '216'],
            ['Turkey', 'Turkish', '90'],
            ['Turkmenistan', 'Turkmen', '993'],
            ['Tuvalu', 'Tuvaluan', '688'],
            ['Uganda', 'Ugandan', '256'],
            ['Ukraine', 'Ukrainian', '380'],
            ['United Arab Emirates', 'Emirati', '971'],
            ['United Kingdom', 'British', '44'],
            ['United States', 'American', '1'],
            ['Uruguay', 'Uruguayan', '598'],
            ['Uzbekistan', 'Uzbek', '998'],
            ['Vanuatu', 'Ni-Vanuatu', '678'],
            ['Vatican City [Holy See]', 'Vatican', '379'],
            ['Venezuela', 'Venezuelan', '58'],
            ['Vietnam', 'Vietnamese', '84'],
            ['Yemen', 'Yemeni', '967'],
            ['Zambia', 'Zambian', '260'],
            [ 'Zimbabwe', 'Zimbabwean', '263']
        ];

        DB::table('country')->insert($data);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('country');
    }
};
